# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "test.db"

lang = "en"
listStyle = "tree"
displayTime = "utc+8"

# ----- App Command to DB Syntax Translation -----
[sqlite3]
list = "SELECT"
add = "INSERT INTO"
edit = "UPDATE"
delete = "UPDATE" # change stauts to "deleted"
