# Choose between: zh-s/zh-f/en
# zh-s == 简体中文; zh-f == 繁体中文(暫未支持)
lang = "en"

# tree/expand
listStyle = "tree"

# >>>need some guidance here<<<
EnableGlobalCommand = false

# Choose between: sqlite3/toml/md/csv/mongodb
# However toml/md/csv/mongodb are not supported in v1.0
DBType = "sqlite3"
DBPath = "test.db"

# 
# utc/utc+-n (UTC-12 ~ UTC+14)
# This will not effect the "uid related" time settings(UTC+0)
displayTime = "UTC+8"


# ----- App Command to DB Syntax Translation -----
[sqlite3]
list = "SELECT"
add = "INSERT INTO"
edit = "UPDATE"


[csv]


[mongodb]


[toml_as_DB]


[md_as_DB]


# ----- helps -----
# 难道用asicⅡ然后根据系统语言转换?
# 或者是单独的.toml/.txt 文本文件也行 <<< 采用这个方案
[command-help]
en = """
Help texts in en
"""

zh-s = """
Help texts in zh-s
"""

[could-not-find]
en = "could not find"
zh-s = "找不到"