# Choose between: zh-s/zh-f/en
# zh-s == 简体中文; zh-f == 繁体中文(暫未支持)
lang = "en"

# Choose between: sqlite3/toml/md/csv/mongodb
# However toml/md/csv/mongodb are not supported in v1.0
[Database]
type = "sqlite3"
path = "test.db"

# >>>need some guidance here<<<
EnableGlobalCommand = false

# tree/expand
listBoardStyle = "tree"

# ----- help Text -----
# 应该是用asicⅡ然后根据系统语言转换?
[commands]
en = """

"""
zh-s = """

"""

[could-not-find]
en = "could not find"
zh-s = "找不到"

