# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "test.db"

lang = "en"
listStyle = "tree"
displayTime = "utc+8"

# ----- App Command to DB Syntax Translation -----
[sqlite3]
# app_command[0] -> command1
"/" = "SELECT name FROM sqlite_master WHERE type='table';"
list = "SELECT "
add = "INSERT INTO "
edit = "UPDATE "
delete = "UPDATE " # change stauts to "deleted"

# app_command[1] -> obj1
board = "TABLE {boardName} "
class = "TABLE {className} "
event = "TABLE {eventName} "

# app_command[2] -> tag1
"-name" = ""
"-d" = ""
"-ddl" = ""
to = "here is to"