# ----- DB Configuration -----
# Just a better reference for dev.db, no functional use(yet)
[Board]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c1 = "status"

[Class]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c3 = "usingBoard"
c4 = "status"

[Event]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c3 = "dscrp"
c4 = "creator"
c5 = "createdTime"
c6 = "classCreated"
c7 = "classCurrent"
c8 = "status"

[Stucked]
c1_pk = "id INTEGER PRIMARY KEY ASC"
c2 = "boardId"
c3 = "eventId"
c4 = "stuckedTime"
c5 = "solvedTime"
c6 = "status"


# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "dev.db"

lang = "en"
listStyle = "tree"
displayTimeZone = "utc+8"


# ----- note -----
# set integer prime key: <columnName> INTEGER PRIMARY KEY ASC
# status: alive/deleted
