# ----- DB Configuration -----
# Just a better reference for dev.db, no functional use(yet)
[Board]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c1 = "status"

[Class]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c3 = "usingBoard"
c4 = "status"

[Event]
c1_p-k = "id INTEGER PRIMARY KEY ASC"
c2 = "name"
c3 = "dscrp"
c4 = "creator"
c5 = "createdTime"
c6 = "classCreated"
c7 = "classCurrent"
c8 = "status"

[Stucked]
c1_pk = "id INTEGER PRIMARY KEY ASC"
c2 = "boardId"
c3 = "eventId"
c4 = "stuckedTime"
c5 = "solvedTime"
c6 = "status"


# ----- App Configuration -----
StrictMode = false
LLM_callable = false

DBType = "sqlite3"
DBPath = "dev.db"

Lang = "en"
ListStyle = "tree"
DisplayTimeZone = "utc+8"


# ----- Some Notes -----
# Set integer prime key: <columnName> INTEGER PRIMARY KEY ASC
# status: alive/deleted/unclassified(event only)
#                                           ↓ Don't foget to write the method(s) for it
# ListStyle: tree/md_table/LLM_md_table/<customName>
# [todo 4] StrickMode: 1. Have to be full length commands; 2. err when not exist