# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "test.db"

lang = "en"
listStyle = "tree"
displayTime = "utc+8"

# ----- App Command to DB Syntax Translation -----
[sqlite3]
# app_command[0]
"/" = "SELECT name FROM sqlite_master WHERE type='table';"
select = "SELECT "
create = "CREATE "
add = "INSERT INTO TABLE "
edit = "UPDATE "
delete = "UPDATE " # change stauts to "deleted"

# app_command[1]
board = "TABLE "
class = "TABLE "
event = "TABLE "
# "/" -> " " in Stateful
stucked = "TABLE "

# app_command[3] && [4]
"-d" = ""
"-ddl" = ""
to = "here is to"
