# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "dev.db"

lang = "en"
listStyle = "tree"
displayTimeZone = "utc+8"


# ----- App Command to DB Syntax Translation -----
[sqlite3.init]
DBType = "sqlite3"
# Table name
Board = ""
Class = ""
Event = ""
Stuck = ""
Alert = ""
DDL = ""

[sqlite3]
# app_command[0]
"/" = "SELECT name FROM Board;"
select = "SELECT "
add = "INSERT INTO "
edit = "UPDATE "
delete = "UPDATE " # change stauts to "deleted"
wipe="DROP WHERE"

# app_command[1]
# board = "({uid}, {name}, {status}).format(uid='', name='', status='live')"
current_board_id = 3
# class = "({uid}, {name}, {usedBoard}, {status})"
current_class_id = 0
# event = "({uid}, {name}, {dscrp}, {createdTime}, {belongBoard}, {classCreated}, {currentClas}, {status})"
current_event_id = 0

# "/" -> " " in Stateful
stucked = "Stucked "

# app_command[3] && [4]
"-d" = ""
"-ddl" = ""
to = "here is to"