# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "test.db"

lang = "en"
listStyle = "tree"
displayTime = "utc+8"

# ----- App Command to DB Syntax Translation -----
[sqlite3]
# app_command[0] -> command1
"/" = "SELECT name FROM sqlite_master WHERE type='table';"
list = "SELECT "
create = "CREATE "
add = "INSERT INTO "
edit = "UPDATE "
delete = "UPDATE " # change stauts to "deleted"

# app_command[1] -> obj1
board = "TABLE {tableName}({uid}, {objName}, {status})"
class = "TABLE {tableName}({uid}, {objName}, {used_board}, {status})"
event = "TABLE {tableName}({uid}, {objName}, {event_dscrp}, {event_creator}, {createdTime}, {class_created}, {ddlTime}, {alertTime}, {currentClass}, {status})"

stucked = "TABLE {tableName}({uid}, {event_uid}, {stucked_time}, {solved_time})"

# app_command[2] -> tag
"-name" = ""
"-d" = ""
"-ddl" = ""
to = "here is to"
