# ----- init Configuration -----
[Board]
# VALUES(?, ?, ?, ...)
c1_p-k = ""
c2 = "name"
c1 = "status" # alive/deleted

[Class]
# VALUES(?, ?, ?, ...)
c1_p-k = ""
c2 = "name"
c3 = "usingBoard"
c4 = "status" # alive/deleted

[Event]
# VALUES(?, ?, ?, ...)
c1_p-k = ""
c2 = "name"
c3 = "dscrp"
c4 = "creator"
c5 = "createdTime"
c6 = "classCreated"
c7 = "classCurrent"
c8 = "status" # alive/deleted

[Stucked]
c1_pk = ""
c2 = "boardId"
c3 = "eventId"
c4 = "stuckedTime"
c5 = "solvedTime"
c6 = "status" # alive/deleted

# ----- App Configuration -----
DBType = "sqlite3"
DBPath = "dev.db"

lang = "en"
listStyle = "tree"
displayTimeZone = "utc+8"
