[boardName_boardUid1]
boardUid.boardName = ""
boardUid.description = ""
# boardUid.creator = ""
boardUid.createdTime = 2023-09-20T03:42:27Z

boardUid.includedNum = 10
boardUid.stackingNum = 1
boardUid.workingNum = 2
boardUid.stuckedNum = 0
boardUid.doneNum = 3
boardUid.archivedNum = 4


# <eventName1>
class0.eventUid.name = ""
class0.eventUid.description = ""
# class0.eventUid.creator = ""
class0.eventUid.createdTime = 2023-09-20T05:14:44Z
class0.eventUid.createdClass = ""
# class0.eventUid.ddlTime = ""
# class0.eventUid.alarmTime = ""
class0.eventUid.currentClass = ""
# class0.eventUid.stackingTime =
# class0.eventUid.workingTime = 
class0.eventUid.stuckedTime = 2023-09-20T05:16:23Z
class0.eventUid.doneTime = 2023-09-20T05:17:47Z
class0.eventUid.archivedTime = 2023-09-20T05:18:34Z


# <evnetName2>
class1.eventUid.name = ""
class1.eventUid.description = ""
# class1.eventUid.creator = ""
class1.eventUid.createdTime = 2023-09-20T05:19:44Z
class1.eventUid.createdClass = ""
# class1.eventUid.ddlTime = ""
# class1.eventUid.alarmTime = ""
class1.eventUid.currentClass = ""
# class1.eventUid.stackingTime =
# class1.eventUid.workingTime = 
class1.eventUid.stuckedTime = 2023-09-20T05:21:23Z
class1.eventUid.doneTime = 2023-09-20T05:22:47Z
class1.eventUid.archivedTime = 2023-09-20T05:23:34Z


[boardName_boardUid2]
# etc...